### ISSUE TITLE
code is not working because "AttributeError: can't set attribute. "

### ISSUE THREAD

**Issue by xjk1354667160** [amar-iastate/L2RPN-using-A3C#4]
my python is 3.8, tf2.0, I ran this code on my conda spyder called  "pypow_14_a3c_final.py" and I got a problem: Using custom reward signal CustomRewardSignal of file F:L2RPN-using-A3C-master\public_data\reward_signal.py Traceback (most recent call last):    File "F\L2RPN-using-A3C-master\pypow_14_a3c_final.py", line 310, in <module>     env = set_environement()    File "F:...\L2RPN-using-A3C-master\pypow_14_a3c_final.py", line 43, in set_environement     game_over_mode=game_over_mode)    File "...\lib\site-packages\pypownet\environment.py", line 812, in __init__     self.reset()    File "C...\lib\site-packages\pypownet\environment.py", line 831, in reset     self.game.n_timesteps_horizon_maintenance)    File "...\lib\site-packages\pypownet\environment.py", line 374, in __init__     self.shape = seek_shapes(self, ())  AttributeError: can't set attribute. I want to seek the reason , can you help me please?

**Comment by dqhzsh** [comment]
> my python is 3.8, tf2.0, I ran this code on my conda spyder called "pypow_14_a3c_final.py" and I got a problem: Using custom reward signal CustomRewardSignal of file F:L2RPN-using-A3C-master\public_data\reward_signal.py Traceback (most recent call last): File "F\L2RPN-using-A3C-master\pypow_14_a3c_final.py", line 310, in env = set_environement() File "F:...\L2RPN-using-A3C-master\pypow_14_a3c_final.py", line 43, in set_environement game_over_mode=game_over_mode) File "...\lib\site-packages\pypownet\environment.py", line 812, in **init** self.reset() File "C...\lib\site-packages\pypownet\environment.py", line 831, in reset self.game.n_timesteps_horizon_maintenance) File "...\lib\site-packages\pypownet\environment.py", line 374, in **init** self.shape = seek_shapes(self, ()) AttributeError: can't set attribute. I want to seek the reason , can you help me please?

Did you solve a problem?

**Comment by Jichao-Wang** [comment]
Repalce "self.shape" by "self._shape" in the whole .py file.

**Comment by hungto3112** [comment]
I had it too, when i use pypownet 2.1.1
Then I used docker to pull pypownet 2.2.9
Problem solved
